// <auto-generated />
using System;
using CinemaApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApp.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20250506140652_Biglietto, Posto, Proiezione, Sala")]
    partial class BigliettoPostoProiezioneSala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CinemaApp.Models.Entities.Biglietto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodicePrenotazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAcquisto")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrezzoFinale")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProiezioneId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostoId");

                    b.HasIndex("ProiezioneId");

                    b.ToTable("Biglietti");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Adulti")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataUscita")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurataMinuti")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocandinaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Valutazione")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Posto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Posti");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Proiezione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SalaId");

                    b.ToTable("Proiezioni");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacitaPosti")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Biglietto", b =>
                {
                    b.HasOne("CinemaApp.Models.Entities.Posto", "Posto")
                        .WithMany("Biglietti")
                        .HasForeignKey("PostoId");

                    b.HasOne("CinemaApp.Models.Entities.Proiezione", "Proiezione")
                        .WithMany("Biglietti")
                        .HasForeignKey("ProiezioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posto");

                    b.Navigation("Proiezione");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Posto", b =>
                {
                    b.HasOne("CinemaApp.Models.Entities.Sala", "Sala")
                        .WithMany("Posti")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Proiezione", b =>
                {
                    b.HasOne("CinemaApp.Models.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaApp.Models.Entities.Sala", "Sala")
                        .WithMany("Proiezioni")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Posto", b =>
                {
                    b.Navigation("Biglietti");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Proiezione", b =>
                {
                    b.Navigation("Biglietti");
                });

            modelBuilder.Entity("CinemaApp.Models.Entities.Sala", b =>
                {
                    b.Navigation("Posti");

                    b.Navigation("Proiezioni");
                });
#pragma warning restore 612, 618
        }
    }
}
